#!/bin/tcsh

set name = $1
echo "name = $name"

#( awk 'NR==6 {print "p0_sp",$1/1000}' infiles/$name.inp ;\
#  awk 'NR==7 {print "th0_sp",$1}'     infiles/$name.inp ) > worksim/$name.param
set P0_SP  = `awk 'NR==6 {print $1/1000}' infiles/$name.inp`
set TH0_SP = `awk 'NR==7 {print $1}'      infiles/$name.inp`
echo "P0_SP, TH0_SP  =  $P0_SP, $TH0_SP"
  
cd src
./mc_single_arm << endofinput >! ../runout/$name.out
$name
endofinput
cd ..

source setup.csh
h2root worksim/$name.rzdat worksim/$name.root

root -b -l <<EOF
  TFile file("worksim/$name.root", "UPDATE");
  TNamed l1("p0_sp", "$P0_SP");
  l1.Write();
  TNamed l2("th0_sp", "$TH0_SP");
  l2.Write();
  file.Close();
EOF

set backslash_quote
root -b -l -q "format_tree.cc(\"$name\")"

#root -b -l -q "analyze_tree.cc(\"$name\")"
